language: node_js
services: postgresql
env: 
  global:
    DATABASE_URL=	postgres://postgres:@localhost:4321/journaldbtest
  - "8"
node_js:
install:
  - npm install
before_script:
  - psql -c 'drop database if exists journaldbtest;' -U postgres
  - psql -c 'create database journaldbtest;' -U postgres
  - npm run db 
  - npm run pretest
script: npm run test
after_success:
  - npm run coveralls
cache:
  directories:
    - "node_modules"
sudo: false
