language: node_js
node_js:
  - "stable"
install:
  - npm install
# before_script:
#  - npm run migrate
# sudo: false 
script: npm run pretest
# services: postgresql
# postgres:
#  adapter: postgresql
#  database: journal_test
#  username: postgres
env: 
  global:
    DATABASE_URL=	postgres://qsvnecfe:gugOIO...@arjuna.db.elephantsql.com:5432/qsvnecfe
#    - PGPORT=4321
#    - DATABASE_URL=<% ENV.fetch('DATABASE_URL', 'postgresql://localhost:4321/journal_test') %>
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coveralls
